name: Get MTV URL

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:      # Enable manual triggering      

jobs:
  get_mtv_url:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium
          pip install selenium_stealth

      - name: Run Python script
        run: |
          cd py  # Change directory to where the script is located
          python videohgtv.py > mtvurl.txt  # Run the script and redirect output

      - name: Commit and Push Changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update token"
          branch: main
          files: |
            py/mtvurl.txt
        env:
          GITHUB_TOKEN: ${{ secrets.ROTANA_TOKEN }}    
