name: Run Script Every 6 Hours

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 */6 * * *'  # Run every 6 hours
  workflow_dispatch:      # Enable manual triggering

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Install curl & base64 CLI
        run: sudo apt-get install -y curl coreutils
        
      - name: Create ar Folder
        run: mkdir -p ar  

      - name: Pull Changes from Remote
        run: git pull origin main        

      - name: Run Script and Generate M3U8 for rotana_Clip
        run: |
         python_output=$(python py/videorclip.py)
         echo "#EXTM3U" > ar/rotanaclip.m3u
         echo "#EXTINF:-1, Rotana Clip" >> ar/rotanaclip.m3u
         echo "$python_output" >> ar/rotanaclip.m3u

      - name: Run Script and Generate M3U8 for rotana_CinemaKSA
        run: |
         python_output=$(python py/videorcinemaksa.py)
         echo "#EXTM3U" > ar/rotanacinema.m3u
         echo "#EXTINF:-1, Rotana Cinema" >> ar/rotanacinema.m3u
         echo "$python_output" >> ar/rotanacinema.m3u           

      - name: Run Script and Generate M3U8 for rotana_CinemaMasr
        run: |
         python_output=$(python py/videorcinemamasr.py)
         echo "#EXTM3U" > ar/rotanacinemamasr.m3u
         echo "#EXTINF:-1, Rotana Cinema Masr" >> ar/rotanacinemamasr.m3u
         echo "$python_output" >> ar/rotanacinemamasr.m3u                      

      - name: Run Script and Generate M3U8 for rotana_KhaleejiyaKSA
        run: |
         python_output=$(python py/videorkhaleejiya.py)
         echo "#EXTM3U" > ar/rotanakhaleejiya.m3u
         echo "#EXTINF:-1, Rotana Khaleejiya" >> ar/rotanakhaleejiya.m3u
         echo "$python_output" >> ar/rotanakhaleejiya.m3u                

      - name: Run Script and Generate M3U8 for rotana_Classic
        run: |
         python_output=$(python py/videorclassic.py)
         echo "#EXTM3U" > ar/rotanaclassic.m3u
         echo "#EXTINF:-1, Rotana Classic" >> ar/rotanaclassic.m3u
         echo "$python_output" >> ar/rotanaclassic.m3u        

      - name: Run Script and Generate M3U8 for rotana_Drama
        run: |
         python_output=$(python py/videordrama.py)
         echo "#EXTM3U" > ar/rotanadrama.m3u
         echo "#EXTINF:-1, Rotana Drama" >> ar/rotanadrama.m3u
         echo "$python_output" >> ar/rotanadrama.m3u                  

      - name: Run Script and Generate M3U8 for rotana_Comedy
        run: |
         python_output=$(python py/videorcomedy.py)
         echo "#EXTM3U" > ar/rotanacomedy.m3u
         echo "#EXTINF:-1, Rotana Comedy" >> ar/rotanacomedy.m3u
         echo "$python_output" >> ar/rotanacomedy.m3u               

      - name: Run Script and Generate M3U8 for rotana_LBC
        run: |
         python_output=$(python py/videorlbc.py)
         echo "#EXTM3U" > ar/rotanalbc.m3u
         echo "#EXTINF:-1, Rotana LBC" >> ar/rotanalbc.m3u
         echo "$python_output" >> ar/rotanalbc.m3u             

      #- name: Run Script and Generate M3U8 for rotana_Kids
      #  run: |
      #    id="rotana_CinemaMasr"
      #    id2="rotana-cinemamasr"
      #    curl_output=$(curl -s "https://rotana.net/en/channels#/live/rotana_CinemaMasr" | grep -oE "https:\\\/\\\/hiplayer.hibridcdn.net\\\/l\\\/rotana-cinemamasr" | sed 's/\\\//\//g' | grep -oE 'https?://[^'\''"]+' | sed 's/CinemaMasr/Kids/g; s/439/441/g; s/Cinema Masr/Kids/g; s/cinemamasr/kids/g' | grep -oE 'https?://[^'\''"]+' | xargs -I {} curl -s "{}" | grep -oP "(?<=o=\[)[^\]]+(?=])" | tr -d "'," | base64 -d | grep -o '"streamUrl":\s*"[^"]*"' | awk -F '"' '{print $4}' | sed 's/playlist\.m3u8/rotana\/kids_720p\/chunks.m3u8/g' | head -n 1)
      #    echo "#EXTM3U" > ar/rotanakids.m3u8
      #    echo "#EXT-X-VERSION:7" >> ar/rotanakids.m3u8
      #    echo "#EXT-X-INDEPENDENT-SEGMENTS" >> ar/rotanakids.m3u8
      #    echo "#EXT-X-STREAM-INF:BANDWIDTH=8000000,CODECS=\"avc1.4d402a,mp4a.40.2\",RESOLUTION=1920x1080,FRAME-RATE=50,AUDIO=\"audio-mp4a.40.2\",CLOSED-CAPTIONS=NONE" >> ar/rotanakids.m3u8
      #    echo "$curl_output" >> ar/rotanakids.m3u8

      #- name: Pull changes from remote
      #  run: git pull origin main

      - name: Commit and Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.ROTANA_TOKEN }}  # Use the stored PAT secret
        run: |
          git config --local user.email "mikekaprielian@vif.com"
          git config --local user.name "Mikekaprielian"
          git add ar/rotanaclip.m3u ar/rotanacinema.m3u ar/rotanaclassic.m3u ar/rotanacomedy.m3u ar/rotanadrama.m3u ar/rotanalbc.m3u ar/rotanacinemamasr.m3u ar/rotanakhaleejiya.m3u
    
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update tokens"
            git push
          fi
